import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    title: 'PMSS – Prime Minister Special Scholarship Scheme',
    subtitle: 'Government of India — Ministry of Education',
    home: 'Home',
    dashboard: 'Dashboard',
    apply: 'Apply Now',
    status: 'Application Status',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    adminLogin: 'Admin Login',
    profileCompletion: 'Profile Completion Score',
    eligibilityCheck: 'AI Eligibility Checker',
    recommendations: 'AI Scholarship Recommendations',
    chatbot: 'AI Scholarship Assistant',
    notifications: 'Notifications',
    verifyQR: 'QR Code Verification',
    transparency: 'Public Transparency Portal',
    accessibility: 'Accessibility Options',
    highContrast: 'High Contrast Mode',
    normalContrast: 'Normal Contrast Mode',
    textSize: 'Text Size',
    voiceNav: 'Voice Commands',
    language: 'Language',
    // Form fields
    personalDetails: 'Personal Details',
    academicDetails: 'Academic Details',
    bankDetails: 'Bank Details',
    documents: 'Document Uploads',
    previewSubmit: 'Preview & Submit',
    fullName: 'Full Name',
    email: 'Email Address',
    phone: 'Phone Number',
    dob: 'Date of Birth',
    state: 'State of Domicile',
    district: 'District',
    aadhaar: 'Aadhaar Card Number',
    income: 'Annual Family Income',
    caste: 'Category / Caste',
    institution: 'Institution Name',
    course: 'Course Name',
    yearOfStudy: 'Year of Study',
    rollNumber: 'Board Roll Number',
    marks: 'Previous Year Marks (%)',
    bankName: 'Bank Name',
    accNo: 'Account Number',
    ifsc: 'IFSC Code',
    submit: 'Submit Application',
    saveDraft: 'Save as Draft',
    ocrBtn: 'AI Auto-Fill (OCR)',
    extracting: 'Extracting details...',
    remarks: 'Reviewer Remarks',
    timeline: 'Application Progress Timeline',
  },
  hi: {
    title: 'पीएमएसएस - प्रधानमंत्री विशेष छात्रवृत्ति योजना',
    subtitle: 'भारत सरकार — शिक्षा मंत्रालय',
    home: 'होम',
    dashboard: 'डैशबोर्ड',
    apply: 'अभी आवेदन करें',
    status: 'आवेदन की स्थिति',
    login: 'लॉगिन',
    register: 'पंजीकरण',
    logout: 'लॉगआउट',
    adminLogin: 'एडमिन लॉगिन',
    profileCompletion: 'प्रोफ़ाइल पूर्णता स्कोर',
    eligibilityCheck: 'एआई पात्रता जाँचकर्ता',
    recommendations: 'एआई छात्रवृत्ति सिफारिशें',
    chatbot: 'एआई छात्रवृत्ति सहायक',
    notifications: 'सूचनाएं',
    verifyQR: 'क्यूआर कोड सत्यापन',
    transparency: 'सार्वजनिक पारदर्शिता पोर्टल',
    accessibility: 'एक्सेसिबिलिटी विकल्प',
    highContrast: 'उच्च कंट्रास्ट मोड',
    normalContrast: 'सामान्य कंट्रास्ट मोड',
    textSize: 'अक्षर आकार',
    voiceNav: 'आवाज आदेश',
    language: 'भाषा',
    personalDetails: 'व्यक्तिगत विवरण',
    academicDetails: 'शैक्षणिक विवरण',
    bankDetails: 'बैंक विवरण',
    documents: 'दस्तावेज़ अपलोड',
    previewSubmit: 'पूर्वावलोकन और सबमिट करें',
    fullName: 'पूरा नाम',
    email: 'ईमेल पता',
    phone: 'फ़ोन नंबर',
    dob: 'जन्म तिथि',
    state: 'मूल राज्य',
    district: 'ज़िला',
    aadhaar: 'आधार कार्ड नंबर',
    income: 'वार्षिक पारिवारिक आय',
    caste: 'श्रेणी / जाति',
    institution: 'संस्थान का नाम',
    course: 'पाठ्यक्रम का नाम',
    yearOfStudy: 'अध्ययन का वर्ष',
    rollNumber: 'बोर्ड रोल नंबर',
    marks: 'पिछले वर्ष के अंक (%)',
    bankName: 'बैंक का नाम',
    accNo: 'खाता संख्या',
    ifsc: 'आईएफएससी कोड',
    submit: 'आवेदन सबमिट करें',
    saveDraft: 'ड्राफ्ट के रूप में सहेजें',
    ocrBtn: 'एआई ऑटो-फिल (ओसीआर)',
    extracting: 'विवरण निकाला जा रहा है...',
    remarks: 'समीक्षक की टिप्पणियाँ',
    timeline: 'आवेदन प्रगति समयरेखा',
  },
  ta: {
    title: 'PMSS – பாரத பிரதமரின் சிறப்பு கல்வி உதவித்தொகை திட்டம்',
    subtitle: 'இந்திய அரசு — கல்வி அமைச்சகம்',
    home: 'முகப்பு',
    dashboard: 'டேஷ்போர்டு',
    apply: 'விண்ணப்பிக்கவும்',
    status: 'விண்ணப்ப நிலை',
    login: 'உள்நுழைக',
    register: 'பதிவு செய்க',
    logout: 'வெளியேறு',
    adminLogin: 'நிர்வாகி உள்நுழைவு',
    profileCompletion: 'விவரம் பூர்த்தி மதிப்பெண்',
    eligibilityCheck: 'AI தகுதி சரிபார்ப்பான்',
    recommendations: 'AI கல்வி உதவித்தொகை பரிந்துரைகள்',
    chatbot: 'AI கல்வி உதவித்தொகை உதவியாளர்',
    notifications: 'அறிவிப்புகள்',
    verifyQR: 'QR குறியீடு சரிபார்ப்பு',
    transparency: 'பொது வெளிப்படைத்தன்மை போர்டல்',
    accessibility: 'அணுகல்தன்மை விருப்பங்கள்',
    highContrast: 'அதிக கான்ட்ராஸ்ட் பயன்முறை',
    normalContrast: 'சாதாரண கான்ட்ராஸ்ட் பயன்முறை',
    textSize: 'எழுத்து அளவு',
    voiceNav: 'குரல் கட்டளைகள்',
    language: 'மொழி',
    personalDetails: 'தனிப்பட்ட விவரங்கள்',
    academicDetails: 'கல்வி விவரங்கள்',
    bankDetails: 'வங்கி விவரங்கள்',
    documents: 'ஆவணங்கள் பதிவேற்றம்',
    previewSubmit: 'முன்னோட்டம் & சமர்ப்பி',
    fullName: 'முழு பெயர்',
    email: 'மின்னஞ்சல் முகவரி',
    phone: 'தொலைபேசி எண்',
    dob: 'பிறந்த தேதி',
    state: 'சொந்த மாநிலம்',
    district: 'மாவட்டம்',
    aadhaar: 'ஆதார் அட்டை எண்',
    income: 'ஆண்டு குடும்ப வருமானம்',
    caste: 'பிரிவு / சாதி',
    institution: 'கல்லூரி பெயர்',
    course: 'பாடநெறி பெயர்',
    yearOfStudy: 'படிக்கும் ஆண்டு',
    rollNumber: 'தேர்வு எண்',
    marks: 'முந்தைய ஆண்டு மதிப்பெண்கள் (%)',
    bankName: 'வங்கி பெயர்',
    accNo: 'கணக்கு எண்',
    ifsc: 'IFSC குறியீடு',
    submit: 'விண்ணப்பத்தை சமர்ப்பி',
    saveDraft: 'வரைவாக சேமி',
    ocrBtn: 'AI ஆட்டோ-பில் (OCR)',
    extracting: 'விவரங்கள் எடுக்கப்படுகிறது...',
    remarks: 'மதிப்பீட்டாளர் கருத்துகள்',
    timeline: 'விண்ணப்ப முன்னேற்ற காலவரிசை',
  },
  te: {
    title: 'పిఎమ్ఎస్ఎస్ - ప్రధానమంత్రి ప్రత్యేక స్కాలర్‌షిప్ పథకం',
    subtitle: 'భారత ప్రభుత్వం — విద్యా మంత్రిత్వ శాఖ',
    home: 'హోమ్',
    dashboard: 'డాష్‌బోర్డ్',
    apply: 'ఇప్పుడే దరఖాస్తు చేసుకోండి',
    status: 'దరఖాస్తు స్థితి',
    login: 'లాగిన్',
    register: 'రిజిస్టర్',
    logout: 'లాగౌట్',
    adminLogin: 'అడ్మిన్ లాగిన్',
    profileCompletion: 'ప్రొఫైల్ పూర్తి స్కోరు',
    eligibilityCheck: 'AI అర్హత తనిఖీదారుడు',
    recommendations: 'AI స్కాలర్‌షిప్ సిఫార్సులు',
    chatbot: 'AI స్కాలర్‌షిప్ సహాయకుడు',
    notifications: 'నోటిఫికేషన్లు',
    verifyQR: 'QR కోడ్ ధృవీకరణ',
    transparency: 'సార్వజనిక పారదర్శకత పోర్టల్',
    accessibility: 'యాక్సెస్బిలిటీ ఎంపికలు',
    highContrast: 'హై కాంట్రాస్ట్ మోడ్',
    normalContrast: 'సాధారణ కాంట్రాస్ట్ మోడ్',
    textSize: 'అక్షరాల పరిమాణం',
    voiceNav: 'వాయిస్ ఆదేశాలు',
    language: 'భాష',
    personalDetails: 'వ్యక్తిగత వివరాలు',
    academicDetails: 'విద్యా వివరాలు',
    bankDetails: 'బ్యాంక్ వివరాలు',
    documents: 'పత్రాల అప్‌లోడ్',
    previewSubmit: 'ప్రివ్యూ & సమర్పించండి',
    fullName: 'పూర్తి పేరు',
    email: 'ఇమెయిల్ చిరునామా',
    phone: 'ఫోన్ నంబర్',
    dob: 'పుట్టిన తేదీ',
    state: 'సొంత రాష్ట్రం',
    district: 'జిల్లా',
    aadhaar: 'आधार నంబర్',
    income: 'వార్షిక కుటుంబ ఆదాయం',
    caste: 'వర్గం / కులం',
    institution: 'కళాశాల పేరు',
    course: 'కోర్సు పేరు',
    yearOfStudy: 'చదువుతున్న సంవత్సరం',
    rollNumber: 'రోల్ నంబర్',
    marks: 'గత సంవత్సరం మార్కులు (%)',
    bankName: 'బ్యాంక్ పేరు',
    accNo: 'ఖాతా సంఖ్య',
    ifsc: 'IFSC కోడ్',
    submit: 'సమర్పించండి',
    saveDraft: 'డ్రాఫ్ట్‌గా సేవ్ చేయండి',
    ocrBtn: 'AI ఆటో-ఫిల్ (OCR)',
    extracting: 'వివరాలు సేకరిస్తున్నారు...',
    remarks: 'రివ్యూయర్ వ్యాఖ్యలు',
    timeline: 'దరఖాస్తు ప్రగతి కాలక్రమం',
  },
  bn: {
    title: 'পিএমএসএস – প্রধানমন্ত্রীর বিশেষ বৃত্তি প্রকল্প',
    subtitle: 'ভারত সরকার — শিক্ষা মন্ত্রক',
    home: 'হোম',
    dashboard: 'ড্যাশবোর্ড',
    apply: 'আবেদন করুন',
    status: 'আবেদনের স্থিতি',
    login: 'লগইন',
    register: 'রেজিস্ট্রেশন',
    logout: 'লগআউট',
    adminLogin: 'অ্যাডমিন লগইন',
    profileCompletion: 'প্রোফাইল সম্পূর্ণতার স্কোর',
    eligibilityCheck: 'এআই যোগ্যতা পরীক্ষক',
    recommendations: 'এআই বৃত্তি সুপারিশ',
    chatbot: 'এআই বৃত্তি সহকারী',
    notifications: 'বিজ্ঞপ্তি',
    verifyQR: 'কিউআর কোড যাচাইকরণ',
    transparency: 'পাবলিক ট্রান্সপারেন্সি পোর্টাল',
    accessibility: 'অ্যাক্সেসিবিলিটি বিকল্প',
    highContrast: 'হাই কনট্রাস্ট মোড',
    normalContrast: 'স্বাভাবিক কনট্রাস্ট মোড',
    textSize: 'হরফ আকার',
    voiceNav: 'ভয়েস কমান্ড',
    language: 'ভাষা',
    personalDetails: 'ব্যক্তিগত বিবরণ',
    academicDetails: 'শৈক্ষিক বিবরণ',
    bankDetails: 'ব্যাঙ্ক বিবরণ',
    documents: 'নথি আপলোড',
    previewSubmit: 'প্রিভিউ এবং সাবমিট',
    fullName: 'সম্পূর্ণ নাম',
    email: 'ইমেল ঠিকানা',
    phone: 'ফোন নম্বর',
    dob: 'জন্ম তারিখ',
    state: 'নিজ রাজ্য',
    district: 'জেলা',
    aadhaar: 'আধার কার্ড নম্বর',
    income: 'বার্ষিক পারিবারিক আয়',
    caste: 'বিভাগ / জাতি',
    institution: 'শিক্ষা প্রতিষ্ঠানের নাম',
    course: 'কোর্সের নাম',
    yearOfStudy: 'অধ্যয়নের বছর',
    rollNumber: 'রোল নম্বর',
    marks: 'গত বছরের প্রাপ্ত নম্বর (%)',
    bankName: 'ব্যাঙ্কের নাম',
    accNo: 'অ্যাকাউন্ট নম্বর',
    ifsc: 'IFSC কোড',
    submit: 'আবেদন জমা দিন',
    saveDraft: 'খসড়া হিসেবে সংরক্ষণ',
    ocrBtn: 'এআই অটো-ফিল (OCR)',
    extracting: 'তথ্য সংগ্রহ করা হচ্ছে...',
    remarks: 'পর্যালোচকের মন্তব্য',
    timeline: 'আবেদন অগ্রগতির টাইমলাইন',
  },
  mr: {
    title: 'पीएमएसएस - पंतप्रधान विशेष शिष्यवृत्ती योजना',
    subtitle: 'भारत सरकार — शिक्षण मंत्रालय',
    home: 'होम',
    dashboard: 'डॅशबोर्ड',
    apply: 'आता अर्ज करा',
    status: 'अर्जाची स्थिती',
    login: 'लॉगिन',
    register: 'नोंदणी',
    logout: 'लॉगआउट',
    adminLogin: 'अ‍ॅडमीन लॉगिन',
    profileCompletion: 'प्रोफाइल पूर्णता स्कोर',
    eligibilityCheck: 'एआय पात्रता तपासणी',
    recommendations: 'एआय शिष्यवृत्ती शिफारसी',
    chatbot: 'एआय शिष्यवृत्ती सहाय्यक',
    notifications: 'सूचना',
    verifyQR: 'क्यूआर कोड पडताळणी',
    transparency: 'सार्वजनिक पारदर्शकता पोर्टल',
    accessibility: 'अ‍ॅक्सेसिबिलिटी पर्याय',
    highContrast: 'हाय कॉन्ट्रास्ट मोड',
    normalContrast: 'सामान्य कॉन्ट्रास्ट मोड',
    textSize: 'अक्षर आकार',
    voiceNav: 'व्हॉइस कमांड',
    language: 'भाषा',
    personalDetails: 'वैयक्तिक तपशील',
    academicDetails: 'शैक्षणिक तपशील',
    bankDetails: 'बँक तपशील',
    documents: 'दस्तऐवज अपलोड',
    previewSubmit: 'पूर्वावलोकन आणि सबमिट',
    fullName: 'पूर्ण नाव',
    email: 'ईमेल पत्ता',
    phone: 'फोन नंबर',
    dob: 'जन्म तारीख',
    state: 'मूळ राज्य',
    district: 'जिल्हा',
    aadhaar: 'आधार कार्ड क्रमांक',
    income: 'वार्षिक कौटुंबिक उत्पन्न',
    caste: 'श्रेणी / जात',
    institution: 'संस्थेचे नाव',
    course: 'अभ्यासक्रमाचे नाव',
    yearOfStudy: 'अभ्यासाचे वर्ष',
    rollNumber: 'बोर्ड रोल नंबर',
    marks: 'मागील वर्षाचे गुण (%)',
    bankName: 'बँकेचे नाव',
    accNo: 'खाते क्रमांक',
    ifsc: 'आयएफएससी कोड',
    submit: 'अर्ज सबमिट करा',
    saveDraft: 'ड्राफ्ट म्हणून जतन करा',
    ocrBtn: 'एी ऑटो-फिल (ओसीआर)',
    extracting: 'माहिती काढत आहे...',
    remarks: 'पुनरावलोकनकर्त्याच्या टिप्पण्या',
    timeline: 'अर्ज प्रगती टाइमलाइन',
  },
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem('pmss_lang') || 'en');

  useEffect(() => {
    localStorage.setItem('pmss_lang', lang);
  }, [lang]);

  const t = (key) => {
    return translations[lang]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => useContext(LanguageContext);
